name: "Testing Pipeline"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: "npm-cache-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: 'npm-cache-'
      - name: Install dependencies
        run: npm install
      - name: eslint
        run: npm run lint
      - name: jest
        run: npm run test
